<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Valider la ligne</name>
   <tag></tag>
   <elementGuidId>2b7bf542-ffff-464e-92f8-7db5e49874a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSuccess</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSuccess']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e0206c9-78e0-43e1-b5c6-19207f09bf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3fee7b7-f5e6-4b45-8226-c758dd74ef64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSuccess</value>
      <webElementGuid>b827e86e-f539-461e-b398-c3cf10b7f743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnValidLine btnSuccess btn-primary</value>
      <webElementGuid>3b81591a-5d75-4b97-a92f-163e9495129e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valider la ligne</value>
      <webElementGuid>53ffdf99-8141-4685-9c35-90aa4699c882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSuccess&quot;)</value>
      <webElementGuid>e57771f8-1f2a-414c-8c49-20b419d2eac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSuccess']</value>
      <webElementGuid>d5255f3e-1b09-4cf1-b5a8-7ead78f5e3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbodyRubriqueNomenclaturesEE']/tr[2]/td[3]/button[2]</value>
      <webElementGuid>d782c803-a9cf-4305-bdb6-466633b49a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effacer la ligne'])[1]/following::button[1]</value>
      <webElementGuid>6c66d51f-3d7b-4e5e-a9cc-67c3041009a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* N° de catégorie et de sous-catégorie'])[1]/following::button[2]</value>
      <webElementGuid>69d94260-b5d0-4ce8-91e4-d5b0b04530bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter une catégorie'])[1]/preceding::button[1]</value>
      <webElementGuid>d1908d88-ccdc-430e-a538-d178fc666e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>cac32269-ec2d-46fe-8765-f346ca685bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnSuccess' and (text() = 'Valider la ligne' or . = 'Valider la ligne')]</value>
      <webElementGuid>ebf36244-9da9-4300-b9f0-30b4a869f987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
