<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_)_demande04</name>
   <tag></tag>
   <elementGuidId>e428df56-0fdb-4912-96a2-5a216aad762d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_checkboxDemande3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_checkboxDemande3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74e2e8e0-892e-44ed-9776-72f4dd1efc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>27eb0747-4550-4dc1-b0b0-a1f03712d030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_checkboxDemande3</value>
      <webElementGuid>9a4d58b2-db5c-4aba-b530-dd05f9d8ad8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unChoixEstRequis</value>
      <webElementGuid>8447e749-fe07-4637-b3bc-7d08f278b8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-chexkboxgroupname</name>
      <type>Main</type>
      <value>demande</value>
      <webElementGuid>5feb84dc-59e8-4116-9450-e1d33cbcc664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fields</name>
      <type>Main</type>
      <value>#input_checkboxDemande0,#input_checkboxDemande1,#input_checkboxDemande2,#input_checkboxDemande3,#input_checkboxEmbarquee0,#input_checkboxEmbarquee1,#input_checkboxEmbarquee2</value>
      <webElementGuid>6cc426a0-d9b6-4f24-9be6-78dd0eb4bb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>cbValidate01</value>
      <webElementGuid>6a17b845-ddf7-4f38-ac05-f83fa8b957f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demande04</value>
      <webElementGuid>9ba89197-a396-4eef-9bdb-3c1b2ba67e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7de182d7-5609-432a-9d34-995bf0060774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_checkboxDemande3&quot;)</value>
      <webElementGuid>0ceba3bb-5a02-4569-8971-386543c7c00e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_checkboxDemande3']</value>
      <webElementGuid>e992741a-ec34-4e04-87ba-847abc00f11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_checkboxDemande3']/input</value>
      <webElementGuid>61d10063-a6b8-43ed-943a-09e8fabad143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>8eb790e1-c53b-41a2-9674-d349ea21137f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'input_checkboxDemande3' and @name = 'demande04']</value>
      <webElementGuid>1a642eca-af77-43a5-80b2-5f62453dd52d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
