<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1 a) Installations classes mentionne_214f93</name>
   <tag></tag>
   <elementGuidId>c6c2ef4c-b897-41f8-96e7-9de19e7e9a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.selectCategorie.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tbodyRubriqueNomenclaturesEE']/tr[2]/td[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cfbbc3fa-662f-4ca7-a1ba-20de6d98bc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCategorie form-control</value>
      <webElementGuid>85e03b0d-3988-4a99-8fec-951ffe07bcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc1d7315-14c3-4471-82ad-59846c840b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>743e8577-b8eb-4625-9181-6f31bd2e50b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>numeroCategorie</value>
      <webElementGuid>e9d88133-b780-494d-9ea0-2d641c2d267a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1° a) Installations classées mentionnées à l’article L.515-28 du CE1° b) Établissements entrant dans le champ de l'article L. 515-32 du CE1° c) Carrières soumises à autorisation mentionnées par la rubrique ICPE 2510 et leurs extensions1° d) Parcs éoliens soumis à autorisation mentionnés par la rubrique ICPE 29801° e) Élevages bovins soumis à autorisation mentionnés par la rubrique ICPE 21011° f) Stockages géologiques de CO2 soumis à autorisation mentionnés par la rubrique ICPE 29702° Installations nucléaires de base3° Installations nucléaires de base secrètes.4° a) Forages pour la recherche des stockages souterrains des déchets radioactifs4° b) Forages pour l'exploitation des stockages souterrains de déchets radioactifs4° c) Installation et exploitation des laboratoires de stockage souterrain des déchets radioactifs5° Voies ferroviaires principales à grande distance6° a) Autoroutes et de voies rapides6° b)  Route à quatre voies ou plus, élargissement d'une route pour en faire une quatre voies ou plus6° c)  Route, élargissement d'une route par ajout d’au moins une voie, extension d’une route7° Tramways, métros, funiculaires ou lignes analogiques8° Aérodromes9° a) Voies navigables et ports de navigation9° b) Ports de commerce, quais de chargement et de déchargement9° c) Ports de plaisance17° Captage ou recharge artificielle  des eaux souterraines21° Barrages23° a) Transvasement de ressources hydrauliques visant à prévenir d’éventuelles pénuries d’eau23° b) Autres cas de transvasement de ressources hydrauliques24° Système d’assainissement25° Extraction de minéraux par dragage marin27° a) Travaux de forage pour l’exploitation  de mines27° b) Travaux de forage géothermique pour l’exploration ou l’exploitation27° c) Travaux de forage de recherches d’hydrocarbures27° d) Travaux de forages de puits pour du stockage souterrain27° e) Travaux d’exploration de mines par forages28° a) Exploitation et travaux miniers à ciel ouvert28° b) Exploitation et travaux miniers souterrains29° Installations destinées à la production d’’énergie hydroélectrique30° Installations photovoltaïques31° Éolienne en mer32° Lignes électriques aériennes en très haute tension33° Lignes électriques en haute et très haute tension en milieu marin37° Canalisations de gaz38° Canalisation pour le transport de fluides autres39° a) Travaux et constructions39° b) Opérations d’aménagement40° Villages de vacances et aménagements associés42° Terrains de camping et de caravanage43° a) Remontées mécaniques ou téléphériques43° b) Pistes de ski (y compris celles dédiées à la luge sans installations fixes)43° c) Installations d’’enneigement et aménagements associés45° Opérations d’aménagements fonciers agricoles et forestières47° a) Défrichements47° b)  Dérogation à l’interdiction de défrichement</value>
      <webElementGuid>8c3924d1-c4fa-4492-84c4-7cbf114a515c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbodyRubriqueNomenclaturesEE&quot;)/tr[@class=&quot;ligneTabActive actif&quot;]/td[@class=&quot;numeroCategorie&quot;]/select[@class=&quot;selectCategorie form-control&quot;]</value>
      <webElementGuid>269f93bf-50c0-4d7b-bf12-42b11e852bfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbodyRubriqueNomenclaturesEE']/tr[2]/td[2]/select</value>
      <webElementGuid>e2fc4556-9eee-4580-b0cb-cb00ca81fd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* N° de catégorie et de sous-catégorie'])[1]/following::select[2]</value>
      <webElementGuid>e71acafc-f4af-4cbf-9170-ec1f7ddd232f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Régime'])[1]/following::select[2]</value>
      <webElementGuid>cddc35e7-d1d5-498d-9e91-b96b882dcb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effacer la ligne'])[1]/preceding::select[1]</value>
      <webElementGuid>1c3e554c-766e-42f2-8f79-9b2fe24a6fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider la ligne'])[1]/preceding::select[1]</value>
      <webElementGuid>8e01d144-f9cc-44bb-8c72-d5f9d50af797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>a1c47d1d-5ebc-47c4-9434-f6ab97dc3dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = concat(&quot;1° a) Installations classées mentionnées à l’article L.515-28 du CE1° b) Établissements entrant dans le champ de l&quot; , &quot;'&quot; , &quot;article L. 515-32 du CE1° c) Carrières soumises à autorisation mentionnées par la rubrique ICPE 2510 et leurs extensions1° d) Parcs éoliens soumis à autorisation mentionnés par la rubrique ICPE 29801° e) Élevages bovins soumis à autorisation mentionnés par la rubrique ICPE 21011° f) Stockages géologiques de CO2 soumis à autorisation mentionnés par la rubrique ICPE 29702° Installations nucléaires de base3° Installations nucléaires de base secrètes.4° a) Forages pour la recherche des stockages souterrains des déchets radioactifs4° b) Forages pour l&quot; , &quot;'&quot; , &quot;exploitation des stockages souterrains de déchets radioactifs4° c) Installation et exploitation des laboratoires de stockage souterrain des déchets radioactifs5° Voies ferroviaires principales à grande distance6° a) Autoroutes et de voies rapides6° b)  Route à quatre voies ou plus, élargissement d&quot; , &quot;'&quot; , &quot;une route pour en faire une quatre voies ou plus6° c)  Route, élargissement d&quot; , &quot;'&quot; , &quot;une route par ajout d’au moins une voie, extension d’une route7° Tramways, métros, funiculaires ou lignes analogiques8° Aérodromes9° a) Voies navigables et ports de navigation9° b) Ports de commerce, quais de chargement et de déchargement9° c) Ports de plaisance17° Captage ou recharge artificielle  des eaux souterraines21° Barrages23° a) Transvasement de ressources hydrauliques visant à prévenir d’éventuelles pénuries d’eau23° b) Autres cas de transvasement de ressources hydrauliques24° Système d’assainissement25° Extraction de minéraux par dragage marin27° a) Travaux de forage pour l’exploitation  de mines27° b) Travaux de forage géothermique pour l’exploration ou l’exploitation27° c) Travaux de forage de recherches d’hydrocarbures27° d) Travaux de forages de puits pour du stockage souterrain27° e) Travaux d’exploration de mines par forages28° a) Exploitation et travaux miniers à ciel ouvert28° b) Exploitation et travaux miniers souterrains29° Installations destinées à la production d’’énergie hydroélectrique30° Installations photovoltaïques31° Éolienne en mer32° Lignes électriques aériennes en très haute tension33° Lignes électriques en haute et très haute tension en milieu marin37° Canalisations de gaz38° Canalisation pour le transport de fluides autres39° a) Travaux et constructions39° b) Opérations d’aménagement40° Villages de vacances et aménagements associés42° Terrains de camping et de caravanage43° a) Remontées mécaniques ou téléphériques43° b) Pistes de ski (y compris celles dédiées à la luge sans installations fixes)43° c) Installations d’’enneigement et aménagements associés45° Opérations d’aménagements fonciers agricoles et forestières47° a) Défrichements47° b)  Dérogation à l’interdiction de défrichement&quot;) or . = concat(&quot;1° a) Installations classées mentionnées à l’article L.515-28 du CE1° b) Établissements entrant dans le champ de l&quot; , &quot;'&quot; , &quot;article L. 515-32 du CE1° c) Carrières soumises à autorisation mentionnées par la rubrique ICPE 2510 et leurs extensions1° d) Parcs éoliens soumis à autorisation mentionnés par la rubrique ICPE 29801° e) Élevages bovins soumis à autorisation mentionnés par la rubrique ICPE 21011° f) Stockages géologiques de CO2 soumis à autorisation mentionnés par la rubrique ICPE 29702° Installations nucléaires de base3° Installations nucléaires de base secrètes.4° a) Forages pour la recherche des stockages souterrains des déchets radioactifs4° b) Forages pour l&quot; , &quot;'&quot; , &quot;exploitation des stockages souterrains de déchets radioactifs4° c) Installation et exploitation des laboratoires de stockage souterrain des déchets radioactifs5° Voies ferroviaires principales à grande distance6° a) Autoroutes et de voies rapides6° b)  Route à quatre voies ou plus, élargissement d&quot; , &quot;'&quot; , &quot;une route pour en faire une quatre voies ou plus6° c)  Route, élargissement d&quot; , &quot;'&quot; , &quot;une route par ajout d’au moins une voie, extension d’une route7° Tramways, métros, funiculaires ou lignes analogiques8° Aérodromes9° a) Voies navigables et ports de navigation9° b) Ports de commerce, quais de chargement et de déchargement9° c) Ports de plaisance17° Captage ou recharge artificielle  des eaux souterraines21° Barrages23° a) Transvasement de ressources hydrauliques visant à prévenir d’éventuelles pénuries d’eau23° b) Autres cas de transvasement de ressources hydrauliques24° Système d’assainissement25° Extraction de minéraux par dragage marin27° a) Travaux de forage pour l’exploitation  de mines27° b) Travaux de forage géothermique pour l’exploration ou l’exploitation27° c) Travaux de forage de recherches d’hydrocarbures27° d) Travaux de forages de puits pour du stockage souterrain27° e) Travaux d’exploration de mines par forages28° a) Exploitation et travaux miniers à ciel ouvert28° b) Exploitation et travaux miniers souterrains29° Installations destinées à la production d’’énergie hydroélectrique30° Installations photovoltaïques31° Éolienne en mer32° Lignes électriques aériennes en très haute tension33° Lignes électriques en haute et très haute tension en milieu marin37° Canalisations de gaz38° Canalisation pour le transport de fluides autres39° a) Travaux et constructions39° b) Opérations d’aménagement40° Villages de vacances et aménagements associés42° Terrains de camping et de caravanage43° a) Remontées mécaniques ou téléphériques43° b) Pistes de ski (y compris celles dédiées à la luge sans installations fixes)43° c) Installations d’’enneigement et aménagements associés45° Opérations d’aménagements fonciers agricoles et forestières47° a) Défrichements47° b)  Dérogation à l’interdiction de défrichement&quot;))]</value>
      <webElementGuid>30654c3d-a6f0-482d-a78a-b0fbedce1e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
