<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cration de la ZAC du Jas du Bouffon_P_f42f36</name>
   <tag></tag>
   <elementGuidId>b3c8776c-eb94-40fa-b4ab-947f5cf70df3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chProjetNom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chProjetNom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c8ebd46-01aa-4bbd-8a2d-a12459b0d84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-5</value>
      <webElementGuid>627ab9d9-2006-4eea-a9e4-97db2cef6989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1df2e1f5-5eb9-4404-ae03-67fa57122364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chProjetNom</value>
      <webElementGuid>88f28e7f-fa56-4995-a7bd-c8581adef71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProjetNom</value>
      <webElementGuid>147785d3-dcdc-4922-aa5d-d11bb57388bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9444600e-c8fd-43dc-ac39-b0ca69acdf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>alphaNum01AtLeastOneLetter</value>
      <webElementGuid>942550dc-d243-4847-9815-4d290bd80f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>de7d816c-cbac-43d7-938c-74d502b0ead7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chProjetNom&quot;)</value>
      <webElementGuid>cb9509ef-d967-4c57-a85f-ad569583268c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chProjetNom']</value>
      <webElementGuid>a94c695f-4362-453f-b763-e8531a399f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_chProjetNom']/input</value>
      <webElementGuid>e868c0dc-bc24-462a-896a-66a8a93d6843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3c83acc6-e0c1-4e72-bde2-2bef02873217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'chProjetNom' and @name = 'ProjetNom']</value>
      <webElementGuid>5db99d0f-9696-4022-a10c-865954eb6ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
