<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Toulouse 31000</name>
   <tag></tag>
   <elementGuidId>6030bb34-4c7b-41d2-bb83-c4af82ea2742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a11y-suggestion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AIOTAddress']/div/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8559fe1-3eb7-4077-8ead-9fc9af528ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a11y-suggestion</value>
      <webElementGuid>db5f3ea1-6d5a-4ed9-8b8c-ea7676fd34f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5b1dd7fe-f2fd-400f-8823-85848fee50f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3c56afa9-5e12-4ad1-b96b-5d2347bb9d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toulouse 31000</value>
      <webElementGuid>b9342415-e950-4aef-9946-bf9b90d75321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AIOTAddress&quot;)/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-md-6 select-a11y&quot;]/div[@class=&quot;a11y-suggestions&quot;]/div[1]/div[@class=&quot;a11y-suggestion&quot;]</value>
      <webElementGuid>2ffda20e-6ad0-42f5-8068-bea9c9f2aec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AIOTAddress']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>5ce4c9d7-2554-4cc5-8e64-c3fdde2f0c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saisie complémentaire requise - affichage automatique'])[1]/following::div[5]</value>
      <webElementGuid>62c84ff7-cf12-4491-b4c5-e2991a258dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localité / Code postal (Exemple: Cesson-Sévigné 35510)'])[1]/following::div[5]</value>
      <webElementGuid>afe7ad19-5fbd-40ba-ae2b-8e40f871110a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::div[2]</value>
      <webElementGuid>8153c242-ded3-470c-afb4-8d1d3b8895b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numéro et voie ou lieu-dit (Exemple : 72 Rue du Douet)'])[1]/preceding::div[2]</value>
      <webElementGuid>2d422971-d7a0-48f1-936e-94ec472d182a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Toulouse 31000']/parent::*</value>
      <webElementGuid>49fbcf04-085a-490b-b7d0-1f2bf0d811a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>f95bad07-ebfa-4f7d-b8e1-78187c7636e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Toulouse 31000' or . = 'Toulouse 31000')]</value>
      <webElementGuid>fea80155-8f4c-4768-a4be-27a2591f99ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
