<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alle des Demoiselles</name>
   <tag></tag>
   <elementGuidId>c87ec622-b15f-4a3c-8fbd-ab69f572286c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a11y-suggestion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AIOTAddress']/div[2]/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6370cf5d-0d3c-4b6c-817d-4b73f71d55d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a11y-suggestion</value>
      <webElementGuid>e7e54557-5bd5-4a69-9bef-176e77292b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4886c4d0-886c-4b96-b52e-cb61529131b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f9902992-c390-40d0-81a0-fe38739a86a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allée des Demoiselles</value>
      <webElementGuid>895bd93a-04a1-4de8-8c65-04daaec96e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AIOTAddress&quot;)/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-md-6 select-a11y&quot;]/div[@class=&quot;a11y-suggestions&quot;]/div[1]/div[@class=&quot;a11y-suggestion&quot;]</value>
      <webElementGuid>97fe1cf8-7e56-449c-93f1-c86d28be5f4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AIOTAddress']/div[2]/div[2]/div[2]/div/div</value>
      <webElementGuid>aa22db6e-e449-4924-ae94-142f57434c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saisie complémentaire requise - affichage automatique'])[2]/following::div[5]</value>
      <webElementGuid>230c0ddb-71e2-487e-8d40-e11288bf854c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numéro et voie ou lieu-dit (Exemple : 72 Rue du Douet)'])[1]/following::div[5]</value>
      <webElementGuid>49307ed2-367e-463f-ad13-0ade335ca6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immeuble - bâtiment - résidence'])[1]/preceding::div[1]</value>
      <webElementGuid>7ba4ee05-f81b-4b5f-8179-70b3d9952213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::div[9]</value>
      <webElementGuid>b7194c17-2b67-4780-aa35-3a310b1d81c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allée des Demoiselles']/parent::*</value>
      <webElementGuid>7d12a24f-511d-4575-8c91-6d206badcef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div</value>
      <webElementGuid>e8c8de4b-3c5e-4067-adb1-56ea09978045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Allée des Demoiselles' or . = 'Allée des Demoiselles')]</value>
      <webElementGuid>7fbb6736-3d0a-447b-8551-aaae988779a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
