<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Votre projet est-il_typeprojet01</name>
   <tag></tag>
   <elementGuidId>787bc671-9a97-4443-9ecb-922b547839ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_checkboxTypeProjet0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_checkboxTypeProjet0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6e9d3a8-643e-4f84-945f-8b72e2efe916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>73fbd2ba-32fe-41b2-af41-9783722b246b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_checkboxTypeProjet0</value>
      <webElementGuid>d2fbc72e-0362-46bd-a07d-84adb542dfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unChoixEstRequis</value>
      <webElementGuid>e06c0d0c-083f-4687-abc3-95e134363d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-chexkboxgroupname</name>
      <type>Main</type>
      <value>typeprojet</value>
      <webElementGuid>42f36b32-bcfb-454c-a636-36945fa52066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeprojet01</value>
      <webElementGuid>36b3226d-d941-4f84-b01d-59fcb0897116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>194d3d8c-194a-48a4-a238-108f1bcd0ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_checkboxTypeProjet0&quot;)</value>
      <webElementGuid>b417521e-3360-4ed7-bc78-6dfccb0d485a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_checkboxTypeProjet0']</value>
      <webElementGuid>4125fac5-e969-4976-95e1-662bd8806881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_checkboxTypeProjet0']/input</value>
      <webElementGuid>0fa08efd-203f-42bd-8040-90e37c25bdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>7f0c8440-adf1-4228-9454-0efc9ba4e8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'input_checkboxTypeProjet0' and @name = 'typeprojet01']</value>
      <webElementGuid>00579726-1194-496e-bb20-c7e6bbb47238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
