<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saisie complmentaire requise - affich_248478</name>
   <tag></tag>
   <elementGuidId>b84c138b-7f3c-4f35-9f1e-f8477b823528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adresseTravaux</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adresseTravaux']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf43efdb-e3f8-4c93-9af8-22ed5e2e2ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adresseTravaux</value>
      <webElementGuid>5966be0c-b44f-4c11-983f-904bba674cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cd223f5e-dfc6-420b-be9c-46c5b4ab41eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autocomplete</value>
      <webElementGuid>55feef2d-2dc8-417c-b57a-f43e6316eef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>adresseBan</value>
      <webElementGuid>afb2a8ee-c246-4e5d-8842-02d41bd4bff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autocomplete-type</name>
      <type>Main</type>
      <value>adresseBan</value>
      <webElementGuid>db0de9ac-b5f2-4e04-8a12-39e2489651ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fdc45709-5a7c-49f9-853b-68cf227b5003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e21671d8-d221-4886-9bc7-09f24f78ce0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0ee1c9e5-3293-49ad-881e-36d609cd2b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adresseTravaux</value>
      <webElementGuid>766eaa43-20ef-4935-bf71-7f8ee08e19e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>messageadresseTravaux</value>
      <webElementGuid>46a020c6-e148-432d-903e-c9a89461caf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>988a13ea-c267-4d16-9f2d-07007a537817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enableautocompletev2</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e716629-d2bc-4c38-844a-72ccd5218df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>formatAdresseBAN</value>
      <webElementGuid>178f1844-dcfc-4000-a3da-5b50d6f50e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-codeinsee</name>
      <type>Main</type>
      <value>31555</value>
      <webElementGuid>87f6d773-2b62-4391-8ab3-1640928ab260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-city</name>
      <type>Main</type>
      <value>Toulouse</value>
      <webElementGuid>4e81f025-bd83-4fd7-b637-a7493fd3cea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zipcode</name>
      <type>Main</type>
      <value>31000</value>
      <webElementGuid>14e862c5-ce24-4914-8d20-c19ce0e0dfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adresseTravaux&quot;)</value>
      <webElementGuid>85023432-6e83-48ea-b270-f3236db5e01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adresseTravaux']</value>
      <webElementGuid>dafd0866-602f-4015-9133-81b169939bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AIOTAddress']/div[2]/div[2]/input</value>
      <webElementGuid>4c6d2057-f9c2-4e26-9fb6-49cbfbfa9d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>0779b638-3c89-49a3-ace5-551af313fa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'adresseTravaux' and @name = 'adresseTravaux' and @type = 'search']</value>
      <webElementGuid>303e054a-ff28-4b9f-ab2f-62334a7e4119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
