<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saisie complmentaire requise - affich_f028f1</name>
   <tag></tag>
   <elementGuidId>7435bb43-daa6-4238-895e-95244f0cb6db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#communeTravaux</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='communeTravaux']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b3123a7-c86e-48e4-99da-8bc4711d4f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>communeTravaux</value>
      <webElementGuid>14ac794a-8920-4f4e-9592-261c1d4cc9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>0d870660-bcf9-4531-bb48-81f140b0fec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autocomplete</value>
      <webElementGuid>ef4d3fcd-3498-4bb9-b9ac-135a60c9740e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>communeBan</value>
      <webElementGuid>e21e80b4-5ef0-4740-bf00-8c2b6b9ce130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autocomplete-type</name>
      <type>Main</type>
      <value>communeBan</value>
      <webElementGuid>8f31f101-7645-43f2-a5c0-80d5112c3e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d08aa262-20f2-4dcd-ba70-5f6b3cf1cc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c01bd316-0ff1-4438-8046-1c7ea2af90a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>d45eaa3d-91de-488a-9790-0f5a864cc5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>communeTravaux</value>
      <webElementGuid>de77d01f-eec0-4135-9767-8617c04b415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>messagecommuneTravaux</value>
      <webElementGuid>0ea20815-208d-430b-a3b0-2028ef6747fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>147b4e13-81f1-4b37-ad97-9fbf2ad46965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enableautocompletev2</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21bf4de6-fde0-40d2-b4f1-521f8934fedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Veuillez saisir le nom de la commune (exemple : Paris)</value>
      <webElementGuid>1dd2a9c2-b3a4-432d-a1c8-3b6542d3aba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>formatCommuneBAN</value>
      <webElementGuid>5f8f42b2-b760-44a4-bfc4-6cd72fe81ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;communeTravaux&quot;)</value>
      <webElementGuid>dca8b09a-4b7c-4acf-8da6-c1fd8f54a077</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='communeTravaux']</value>
      <webElementGuid>b544fe6b-73c4-4832-a01b-f65b794e6f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AIOTAddress']/div/div[2]/input</value>
      <webElementGuid>90bca42d-d552-4e6e-ad42-a4f7faf92436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f9e252d4-0979-462a-bdd7-01e725752dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'communeTravaux' and @name = 'communeTravaux' and @type = 'search' and @placeholder = 'Veuillez saisir le nom de la commune (exemple : Paris)']</value>
      <webElementGuid>0a4ddb1a-0338-4b30-9095-03d496ba289b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
