<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Prcdent</name>
   <tag></tag>
   <elementGuidId>0081e3fb-99b8-46d1-bfb2-598abbba2f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#precedent > span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='precedent']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>90ff05fe-cb49-4691-b278-0114caa09b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>12422976-a074-4e31-bae6-eb4f09e4e770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Précédent</value>
      <webElementGuid>02940a85-c108-4664-920e-b9bea7bdf5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;precedent&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>c780a835-1a82-4ab9-8dea-acb1902f6016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='precedent']/span</value>
      <webElementGuid>3d67fcdb-4fd1-457f-aece-620920da2d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zip'])[1]/following::span[1]</value>
      <webElementGuid>92315efb-1672-4b3d-ad13-19a7655d9d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reprendre plus tard'])[1]/preceding::span[1]</value>
      <webElementGuid>b95d7c28-f46e-4db8-b6eb-65a5aa9c4108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suivant'])[1]/preceding::span[2]</value>
      <webElementGuid>c7dd9232-a026-4cfb-aa27-cd0672f0bf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Précédent']/parent::*</value>
      <webElementGuid>eec465a3-2868-47b0-901b-fef60bbb7f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button/span</value>
      <webElementGuid>fe8a0156-201e-4156-ab09-f7d692babc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Précédent' or . = 'Précédent')]</value>
      <webElementGuid>3b57126e-51a4-4945-af46-544bd2d16f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
