<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Depuis mon ordinateur</name>
   <tag></tag>
   <elementGuidId>08ef6269-24fc-4c79-8053-dde5df71ed09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#depuisOrdiPiecesJointes_fichierParcellesUploade</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='depuisOrdiPiecesJointes_fichierParcellesUploade']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c91425a-d5cf-4a09-b671-484677f6ff22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depuisOrdiPiecesJointes_fichierParcellesUploade</value>
      <webElementGuid>a9ac93a9-6dd0-4758-98ff-6db3459d562e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Depuis mon ordinateur</value>
      <webElementGuid>5804bc28-0cf8-43c1-a416-21b456cd3298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;depuisOrdiPiecesJointes_fichierParcellesUploade&quot;)</value>
      <webElementGuid>594f654d-ed8b-4a1e-9cb2-e7434ca44a95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='depuisOrdiPiecesJointes_fichierParcellesUploade']</value>
      <webElementGuid>6f33ab4d-95ad-4328-b223-81db88f64a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploadBolc_PiecesJointes_fichierParcellesUploade']/div/button/span</value>
      <webElementGuid>14ba42d1-b4c4-4110-a9dc-0943ecd836ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='??daenv.composant.fichierParcellesUploade.help.description_fr??'])[1]/following::span[1]</value>
      <webElementGuid>e854f148-4b59-4a84-aa72-620c5f7ae6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter un fichier :'])[1]/following::span[3]</value>
      <webElementGuid>4aaf7196-6c73-4ca7-a04e-53944668261a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='csv'])[1]/preceding::span[2]</value>
      <webElementGuid>a282fabe-c311-47e8-a744-dbb9a1189a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Depuis mon ordinateur']/parent::*</value>
      <webElementGuid>c2cda245-0048-462c-bc9a-7f8944510cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span</value>
      <webElementGuid>47aee5c5-4167-40a2-ac47-e131ffe62e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'depuisOrdiPiecesJointes_fichierParcellesUploade' and (text() = '
										Depuis mon ordinateur' or . = '
										Depuis mon ordinateur')]</value>
      <webElementGuid>719925e1-a0de-4dfe-9ff8-e8ae3f50bd8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
