<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Valider</name>
   <tag></tag>
   <elementGuidId>8327a83e-1d26-4272-9166-a1d38131804f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alertPopinBtnOui > span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='alertPopinBtnOui']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfe1213c-d852-41c2-b21c-3b9cdb13b93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>f4950e96-fbf9-4713-99ef-53f4f7fffa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>6c668c68-532c-4a0e-ad11-5f33e8147c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertPopinBtnOui&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>fc746449-5a1c-4f18-a8fb-72cf15c5584a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='alertPopinBtnOui']/span</value>
      <webElementGuid>bdf924f7-e9df-4322-8852-9721dd1e1bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libellé de voie'])[1]/following::span[2]</value>
      <webElementGuid>5662c961-82f7-4d9a-a3b7-053c3bc4eea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::span[3]</value>
      <webElementGuid>8e037f5b-8799-42fb-a5fb-4e33084a4fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annuler'])[6]/preceding::span[1]</value>
      <webElementGuid>b033a23a-fe7b-4f59-9bca-26482e4afc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button/span</value>
      <webElementGuid>d4a43a8c-143c-426f-a051-fe2f4f822f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Valider' or . = 'Valider')]</value>
      <webElementGuid>4b86fa88-df37-4c85-8aca-ec806458a944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
