<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accepter</name>
   <tag></tag>
   <elementGuidId>e45f0222-efd4-4023-bbce-1a9b1d8586fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.orejime-Button.orejime-Button--save.orejime-Notice-button.orejime-Notice-saveButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d26f67a8-fccb-4940-8d8f-56b6fc1faf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orejime-Button orejime-Button--save orejime-Notice-button orejime-Notice-saveButton</value>
      <webElementGuid>41f4c48a-96cd-41a5-abf1-f1a4bbfd3881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc063a99-ac6b-4cad-8b41-192322ba3528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Accepter les cookies</value>
      <webElementGuid>46712eef-1145-4154-9bff-1174cb6f56e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xiti-name</name>
      <type>Main</type>
      <value>orejime::accepter::::</value>
      <webElementGuid>4a645cd9-5543-4b4e-888b-14816e9aba4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xiti-type</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>c7a9862e-091d-4a27-8f8f-6708b7b74741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepter</value>
      <webElementGuid>d6a81dd9-e907-4f56-a5c0-2c45f839710a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orejime&quot;)/div[@class=&quot;orejime-AppContainer&quot;]/div[@class=&quot;orejime-Main&quot;]/div[@class=&quot;orejime-Notice&quot;]/div[@class=&quot;orejime-Notice-body&quot;]/ul[@class=&quot;orejime-Notice-actions&quot;]/li[@class=&quot;orejime-Notice-actionItem orejime-Notice-actionItem--save&quot;]/button[@class=&quot;orejime-Button orejime-Button--save orejime-Notice-button orejime-Notice-saveButton&quot;]</value>
      <webElementGuid>3ed0fb0f-e5be-4120-b02c-30408156c52a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>1d5cfe16-0ad4-4125-b6d3-a59a5f2b5a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orejime']/div/div/div/div/ul/li/button</value>
      <webElementGuid>ce196b21-ee49-421d-90fe-3db4e3674030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refuser'])[1]/preceding::button[1]</value>
      <webElementGuid>1cccc230-c266-4921-be92-37cc0e36a6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gérer les cookies'])[1]/preceding::button[2]</value>
      <webElementGuid>d2c9da26-455f-46ff-8e30-cf8b4550c2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>20d95c20-5e5b-4c56-abd6-8fc9951cbf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Accepter les cookies' and (text() = 'Accepter' or . = 'Accepter')]</value>
      <webElementGuid>6492cd2c-fd23-4db8-ac75-49c8d1f0f149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
