<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oui_chServInst</name>
   <tag></tag>
   <elementGuidId>636c8952-e57f-408e-a3b1-e56e5054530e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioServInst1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioServInst1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8dfd00b-3460-4d61-98eb-af12c41b7d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>085ddd2b-5a5f-44ac-a170-23e89ec0ec6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>39ed9d05-9c20-4185-92ea-de1fecbab0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>91f49b9b-47b3-4de3-a6bf-81e424ea8442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target</name>
      <type>Main</type>
      <value>#dmd_COND03</value>
      <webElementGuid>120cb9b6-5d5c-4d2d-8fa0-9b83f3b0647d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target-inverse</name>
      <type>Main</type>
      <value>#dmd_COND02</value>
      <webElementGuid>f37756f7-fa41-4feb-93c0-bd049122bca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-condition</name>
      <type>Main</type>
      <value>NON</value>
      <webElementGuid>7f0739bd-dfbf-4db0-9104-fbce76527ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioServInst1</value>
      <webElementGuid>0fd8b85b-da00-49e1-80a3-e765c24c010c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NON</value>
      <webElementGuid>07e1f3c6-a60a-4521-8bc0-9d316b70b383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chServInst</value>
      <webElementGuid>e2686212-778b-4276-a254-a717544d3d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioServInst1&quot;)</value>
      <webElementGuid>7c688871-f76a-48d0-a812-577d62e8b22c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioServInst1']</value>
      <webElementGuid>82bd08e2-f968-44f8-a345-611c43b2e525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioServInst1']/input</value>
      <webElementGuid>c3d15a88-7461-4a2f-a5e7-7c79dd3cd470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oui'])[1]/following::input[1]</value>
      <webElementGuid>92a40a1a-b83e-4231-bfb4-f8e43aabb143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saisie complémentaire requise - affichage automatique'])[2]/following::input[2]</value>
      <webElementGuid>5180540a-f2fd-41a4-8c72-e21a8af7f151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non'])[1]/preceding::input[1]</value>
      <webElementGuid>a2c09a68-bed7-42fe-b1b2-75d38716c6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='la D(R)EAL, la DRIEAT ou la DGTM'])[1]/preceding::input[2]</value>
      <webElementGuid>90186ddb-59fa-4cfb-9f9b-0c9f4707a425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>9b23d942-9fd6-4da6-a5d9-96934f4ad631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioServInst1' and @name = 'chServInst']</value>
      <webElementGuid>c501a6d0-4aba-410d-a524-a2429bd4b4b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
