<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__infoReglo</name>
   <tag></tag>
   <elementGuidId>be4bc322-f680-459a-bac8-e529050eb393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_checkboxCGN0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_checkboxCGN0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74c12fe1-33e8-4a6e-bc0a-5185ac0b1562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>41ed0fe3-a5b9-4f01-868f-6ab795b4fa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_checkboxCGN0</value>
      <webElementGuid>4617ba6d-158c-4a39-9db6-39e9b36c37a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>03e05404-0d4f-4963-8c9b-96750ba44449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>infoReglo</value>
      <webElementGuid>e443d00a-8c3c-40d6-9ec8-fbca73e5d43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f785b3af-b974-4202-8889-9d3eb75b521e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_checkboxCGN0&quot;)</value>
      <webElementGuid>1ef21b01-eb36-4598-8e9e-1a6a0ff1a1cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_checkboxCGN0']</value>
      <webElementGuid>8295dd82-8748-44fa-b796-783a241ac55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_checkboxCGN0']/input</value>
      <webElementGuid>02f6da4e-bd06-47fe-9d86-f87c633f6972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::input[1]</value>
      <webElementGuid>efd21620-ae26-46c8-ae57-758a1ca874c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::input[2]</value>
      <webElementGuid>9485cf52-6cf8-4f9b-afee-fed542b58aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/label/input</value>
      <webElementGuid>0d3b171f-7c5c-4d3d-84c4-e7f22320c114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'input_checkboxCGN0' and @name = 'infoReglo']</value>
      <webElementGuid>920727a9-4fe3-4c5b-b63b-9515ef6d6a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
