<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saisie complmentaire requise - affich_3e6a9c</name>
   <tag></tag>
   <elementGuidId>afedec22-66a8-4684-a40c-9a964d7d7abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioINIT0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioINIT0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcd1ae2d-cb30-452c-a523-9f0f81339443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3531843e-d67e-4759-b514-ecaf15583d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>194db535-568e-4ff6-8bf7-8add46aa74c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>daa7c7c1-189b-47fc-a2b2-854f300fcb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target</name>
      <type>Main</type>
      <value>#dmd_COND01</value>
      <webElementGuid>27f8f3ca-698a-4e6a-bb1c-e25768268fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-condition</name>
      <type>Main</type>
      <value>INIT</value>
      <webElementGuid>8bee7aa1-fc01-460d-869a-eceba1180f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioINIT0</value>
      <webElementGuid>5fa3a935-b53b-4337-9683-31b97b69188b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>INIT</value>
      <webElementGuid>ea1a1443-1770-42ea-afd6-c8cbf94a7835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chTypeDmd</value>
      <webElementGuid>ffb18d05-af87-480c-af3d-64320441701f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioINIT0&quot;)</value>
      <webElementGuid>559c150e-e92d-4c26-9ee7-ae307e435ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioINIT0']</value>
      <webElementGuid>51511a2c-a8a2-4309-9a28-61d30a88f99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioINIT0']/input</value>
      <webElementGuid>58c3dd06-4428-4762-9b05-7b97849af516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saisie complémentaire requise - affichage automatique'])[1]/following::input[1]</value>
      <webElementGuid>a3f49caa-711b-4e1e-8b08-bcf05ad937b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quelle est la démarche dont vous avez besoin ?'])[1]/following::input[1]</value>
      <webElementGuid>2d986460-24f5-4d33-bd74-225f5df51232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Démarrer le dépôt d', &quot;'&quot;, 'un dossier de demande d', &quot;'&quot;, 'autorisation environnementale.')])[1]/preceding::input[1]</value>
      <webElementGuid>5be8a045-7e94-46a4-948c-5ec09baf06ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Aide sur le dépôt d', &quot;'&quot;, 'un dossier')])[1]/preceding::input[1]</value>
      <webElementGuid>4c2b276e-e273-4867-a637-df631a9d7128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aa0e52d7-1ba8-4725-823c-1f304b14c2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioINIT0' and @name = 'chTypeDmd']</value>
      <webElementGuid>4851d132-0cb4-4334-87c8-0b5f92c83bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
