<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numro dAIOT (le numro dAIOT doit comp_63a726</name>
   <tag></tag>
   <elementGuidId>518f89fd-33f1-4361-b374-e24b710ae789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noAIOT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noAIOT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7093cc42-75c8-421f-8aab-64ca7dd5e653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7ea0702b-d65d-43df-a236-40c74c969ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1941ff9-58d0-4dae-b342-9980fffb9afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noAIOT</value>
      <webElementGuid>08aed4a1-4c85-4685-96b4-4f9801d87a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noAIOT</value>
      <webElementGuid>6298ccb4-4924-4928-a48b-6d56f2611e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1586d577-96d2-4005-b819-d527aa34d181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noAIOT&quot;)</value>
      <webElementGuid>8f7265e1-89aa-4d78-8778-5078c802ba55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noAIOT']</value>
      <webElementGuid>315e394f-26de-46b9-ae47-59bcc81b3bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_numeroAIOT']/p/label/input</value>
      <webElementGuid>15cd2c84-9203-488f-9890-336b9a30161a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numéro d’AIOT (le numéro d’AIOT doit comporter 10 chiffres, exemple 0040987214)'])[1]/following::input[2]</value>
      <webElementGuid>a52f8719-075d-47dc-b513-02743a1996be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Je ne connais pas mon numéro d', &quot;'&quot;, 'AIOT')])[1]/preceding::input[2]</value>
      <webElementGuid>ed2c39c5-786d-42f8-8bfb-50a328c02971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::input[2]</value>
      <webElementGuid>1bbab61a-131c-416b-8f0d-34916e4e2ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/label/input</value>
      <webElementGuid>afa8ab7f-7446-45b7-bf11-70f3b17ae137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'noAIOT' and @id = 'noAIOT']</value>
      <webElementGuid>295a2040-1c97-421e-94c9-b6f3cbdac9d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
