<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pieceConf</name>
   <tag></tag>
   <elementGuidId>53ecb6ad-5d45-42c0-9219-952753f8cbe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_checkboxCGN1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_checkboxCGN1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfa75848-f81c-46a4-ac7f-ec5a357b13bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f35731c-e4ed-43c3-943e-107c03b59787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_checkboxCGN1</value>
      <webElementGuid>fb181c4a-a35e-4f5e-9ded-21aee1386e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d098399b-5bec-4771-9baf-6a8bba3dab50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pieceConf</value>
      <webElementGuid>b39a1f00-06c5-4627-b659-8b6405b82b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7271962-3470-464e-b22c-c4dec58ca9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_checkboxCGN1&quot;)</value>
      <webElementGuid>55d58c7f-d23a-4d3d-9a55-a71a1aafa023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_checkboxCGN1']</value>
      <webElementGuid>b0e296c2-2317-4c97-a811-75e3ba3e193c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_checkboxCGN1']/input</value>
      <webElementGuid>63dbf6e9-04e3-4a2d-ad0c-a069f8a0db78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::input[1]</value>
      <webElementGuid>410bdb06-35e4-4caa-8a78-8b01e6bad662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(R. 181-12)'])[1]/preceding::input[2]</value>
      <webElementGuid>552ababb-0e8b-4e94-a042-11a6442224f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/label[2]/input</value>
      <webElementGuid>2dfc69fc-a7c3-4c6d-babb-1f7fdafe722d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'input_checkboxCGN1' and @name = 'pieceConf']</value>
      <webElementGuid>e06dacb5-be9c-41dd-8bae-1405c658ad8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
