<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Suivant</name>
   <tag></tag>
   <elementGuidId>7f1d7e12-61a5-4d85-916b-0538079f8a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='suivant']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac002dd6-8287-4ee7-91f1-18c26c011df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>76a90ce9-0008-4ef7-a5ef-d0f411662f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>16a5db5e-20a5-4455-b54c-327788b9179d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suivant&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>40049d0c-2ee5-4da1-abb2-e476f371c1d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='suivant']/span</value>
      <webElementGuid>998229f6-89d2-49bb-aec9-7eba07134619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::span[3]</value>
      <webElementGuid>872fa7c8-3693-4f3f-8869-ba6618bc082a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lettre Service-Public'])[1]/preceding::span[2]</value>
      <webElementGuid>7cdeb3de-8d36-4a30-99cf-ed95aeb9abe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::span[3]</value>
      <webElementGuid>515eda4e-e8a7-44b6-8206-2289fe997257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button/span</value>
      <webElementGuid>fd2e0b54-5062-413b-bf34-4f0a04767ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Suivant' or . = 'Suivant')]</value>
      <webElementGuid>d504bc32-7f17-4b0f-9b02-537d1a0c325f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
