<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Suivant</name>
   <tag></tag>
   <elementGuidId>5f65a270-cfc2-4d1f-be4e-6f57b65d66fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suivant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='suivant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a8f9526-4743-48c5-b92f-f4b6ddb13a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-next mobilable</value>
      <webElementGuid>f569d264-2c79-4c4f-b88d-35bae978f06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a0bc6a46-0ef0-4fe3-8a09-f0874bcae8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suivant</value>
      <webElementGuid>f93f513e-2e11-44a7-b53b-c0db0d765e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_eventId_suivant</value>
      <webElementGuid>6ec3feeb-c7b8-45cf-9e35-c3de4a749036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>921ba21f-c3c4-4c37-9654-0953a62d78c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suivant&quot;)</value>
      <webElementGuid>2852388b-283f-4b71-8b24-615efb073c63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='suivant']</value>
      <webElementGuid>a88958d8-9b96-4658-b9df-b105e9160e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='page-localisation']/div[9]/nav/button[3]</value>
      <webElementGuid>71481f3e-cf9e-4226-8a9c-5eba9f1543d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reprendre plus tard'])[1]/following::button[1]</value>
      <webElementGuid>668e2249-e53c-4dee-b830-e86dab94e321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Précédent'])[1]/following::button[2]</value>
      <webElementGuid>c3d3a6b0-1284-4663-9238-437c29825bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attention'])[2]/preceding::button[3]</value>
      <webElementGuid>a9b2ca7e-38c8-4137-96ab-4b5d27cbe2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button[3]</value>
      <webElementGuid>dce818c4-c1ca-4183-b080-0f9ccec38f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'suivant' and @name = '_eventId_suivant' and (text() = 'Suivant' or . = 'Suivant')]</value>
      <webElementGuid>ce661ae9-4c86-40eb-8767-7504435da5f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
