<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N_redr_numero</name>
   <tag></tag>
   <elementGuidId>696ea166-9fda-4a54-9f07-d42aee106457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#redr_numero</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='redr_numero']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7038ea3b-ed79-4a1a-9b1d-2cd3a9fb859e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>651a049a-71ed-4fab-8e59-88412d764d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control static</value>
      <webElementGuid>a4045a0f-2d91-4b68-b76e-d938a0ac757a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redr_numero</value>
      <webElementGuid>36e8a684-38c8-42df-bc9c-5d7d38aeab81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef9ce08b-7a3e-4614-8e6d-61716eb52f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>tailleMax doubleNumeric</value>
      <webElementGuid>384978c4-35b9-4ee5-922c-e712cb9120b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-max</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>48c42c72-6152-4bb7-875a-0eb20e5fd8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ec1f4f10-394e-433d-87bf-253c8d8881e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>textDanger25</value>
      <webElementGuid>df4fbd0f-4e12-443d-ac03-5e8597bd59e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redr_numero&quot;)</value>
      <webElementGuid>d54cdb92-d420-49df-a755-dfb114fcdc88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='redr_numero']</value>
      <webElementGuid>6a6d9120-65df-4278-92ee-9f5e4f77a726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalConfirmation1']/div[2]/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>ed9a8d27-5a57-46d3-92ae-3a8e489da73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/input</value>
      <webElementGuid>c58aec9a-3f5d-4c76-a06a-44347b7a8033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'redr_numero']</value>
      <webElementGuid>17ccfd60-d20a-40c0-b642-6af2b6bd8f88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
