<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Prcdent</name>
   <tag></tag>
   <elementGuidId>949a1857-308a-49d7-998d-b1f071331ee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#precedent > span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='precedent']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1b58c244-c92c-4cfc-b7fc-71583d26bdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>a4ed7a88-eda7-4224-89c1-d6b74a368e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Précédent</value>
      <webElementGuid>647bec14-44b7-42d2-939b-e5ce0c2f302a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;precedent&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>504efce1-7998-423e-b6d2-4ab205708aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='precedent']/span</value>
      <webElementGuid>7b72db12-3fdd-410d-9018-a890c2b61fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zip'])[1]/following::span[1]</value>
      <webElementGuid>3e18e75b-3967-439e-b1f0-cd8c03217257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reprendre plus tard'])[1]/preceding::span[1]</value>
      <webElementGuid>149b642d-81f2-410f-a6fc-f8486ac51453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suivant'])[1]/preceding::span[2]</value>
      <webElementGuid>c2105123-580a-4c6f-9e96-9f5f552189de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Précédent']/parent::*</value>
      <webElementGuid>9d27d3b1-47ad-475f-b8d8-8b30bdd97826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button/span</value>
      <webElementGuid>e9447036-49ba-4f19-a6e1-a1eb99813ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Précédent' or . = 'Précédent')]</value>
      <webElementGuid>82386ea6-0ff6-41b5-b951-d127de2aba48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
