<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Suivant</name>
   <tag></tag>
   <elementGuidId>91dc2f27-388d-4b67-bf66-5746a934d2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suivant > span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='suivant']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>869505ca-4cee-4e24-9a36-36117bb0ad40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>fd2532c6-d395-49dc-9c0a-47608e9f3cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>a3a140db-dbbf-4b8c-bbd0-3e80637924e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suivant&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>98a10c9d-19de-4de0-bc9b-c8884b6ff9fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='suivant']/span</value>
      <webElementGuid>75956020-4774-45b6-b661-05f778320057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reprendre plus tard'])[1]/following::span[1]</value>
      <webElementGuid>a21ef03d-56ee-4cdd-86e8-2a08aa1ea21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Précédent'])[1]/following::span[2]</value>
      <webElementGuid>318ee317-40ee-4a9e-8861-4eeae223783d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attention'])[2]/preceding::span[2]</value>
      <webElementGuid>5ec94d80-69dc-43ae-8b65-ddecc3d11c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attention'])[3]/preceding::span[2]</value>
      <webElementGuid>fc878318-1dc5-4b48-9e9d-bd656bb5c6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suivant']/parent::*</value>
      <webElementGuid>252eb2e8-0bc5-41a8-b673-8b8ce5e7f28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button[3]/span</value>
      <webElementGuid>ba633de9-b212-4771-b00d-aa7d5250ea9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Suivant' or . = 'Suivant')]</value>
      <webElementGuid>1cf21453-0ae6-479a-acc1-e1c5d2f49dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
