<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Valider</name>
   <tag></tag>
   <elementGuidId>aa48ef9a-06b9-4bea-a8c8-80a551a728fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alertPopinBtnOui > span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='alertPopinBtnOui']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2886cb19-566b-481f-aa68-59a6b81d44b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>eb74e37d-6b01-46f7-95e6-3fe0d5a4a2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>0a7167ab-2220-44a7-a3a8-1b15abefe62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertPopinBtnOui&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>c8f506f8-8804-44f6-b692-e68fb3dda0e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='alertPopinBtnOui']/span</value>
      <webElementGuid>666d119c-e7b9-40a6-b358-99c8b3d0fa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libellé de voie'])[1]/following::span[2]</value>
      <webElementGuid>e75cc37d-cf51-4570-bb99-1de20747f11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::span[3]</value>
      <webElementGuid>79ee4901-bff1-4242-8f4f-1b40dd739d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annuler'])[6]/preceding::span[1]</value>
      <webElementGuid>24a83fc0-0ae9-481f-8a8f-721c1cba685b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button/span</value>
      <webElementGuid>771297dc-7f82-4225-b7f5-be2cba9572de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Valider' or . = 'Valider')]</value>
      <webElementGuid>1b28fa52-0bde-4a12-934d-b33374b62413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
