<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_confirmer la demande</name>
   <tag></tag>
   <elementGuidId>7726824d-534e-48e4-a06a-e807c27d88ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suivant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='suivant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c32f07c-754d-4066-827f-de175d9634f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-next mobilable</value>
      <webElementGuid>dcab728c-4c21-4458-a9be-749e5d2abda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>642e661d-bd43-4775-9252-fc94bcab8110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suivant</value>
      <webElementGuid>15cbd1bf-89e3-4a91-9e08-71f1c6e2ed3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_eventId_suivant</value>
      <webElementGuid>8aa5c864-f9f6-494d-a32f-f37c29d9685f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>confirmer la demande</value>
      <webElementGuid>6ad07fee-9080-4655-a107-7cf481ebc529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suivant&quot;)</value>
      <webElementGuid>a4be622c-55d5-45da-8b78-ee42e29be922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='suivant']</value>
      <webElementGuid>32f26fd3-c6a0-4bd4-85f5-48e27740cf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[3]/form/div[12]/nav/button[3]</value>
      <webElementGuid>4cfc440d-450a-4d72-8f50-5b8bfb5674c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reprendre plus tard'])[1]/following::button[1]</value>
      <webElementGuid>03dc4667-9883-4852-8160-338a91040a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Précédent'])[1]/following::button[2]</value>
      <webElementGuid>8b67a424-2422-46f0-b722-09119b8f0ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lettre Service-Public'])[1]/preceding::button[1]</value>
      <webElementGuid>37b964a9-1fd2-43d6-bfe9-9c5d0912abbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::button[1]</value>
      <webElementGuid>abfdcc42-b9f9-43cb-8267-03ae68f06fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='confirmer la demande']/parent::*</value>
      <webElementGuid>7bcc2d81-a5f7-45da-93c8-e1b4fae86b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>d5145dfb-c6b6-4084-8c23-1e9c3538860f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'suivant' and @name = '_eventId_suivant' and (text() = 'confirmer la demande' or . = 'confirmer la demande')]</value>
      <webElementGuid>49d367ed-4af6-4728-9edb-e84baf2bfd31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
