<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Depuis mon ordinateur</name>
   <tag></tag>
   <elementGuidId>ff9c0132-25f3-4257-a053-8f16b648b0a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#depuisOrdiPiecesJointes_maitriseFonciere</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='depuisOrdiPiecesJointes_maitriseFonciere']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3abb709f-d6f4-41cd-827b-f3e87b4e08d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depuisOrdiPiecesJointes_maitriseFonciere</value>
      <webElementGuid>580f3040-9245-4b65-ac6d-5fa1a0296848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Depuis mon ordinateur</value>
      <webElementGuid>2d499d9c-1332-4c4c-9ec9-56caccc8df4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;depuisOrdiPiecesJointes_maitriseFonciere&quot;)</value>
      <webElementGuid>2e477f81-29c3-4601-85d9-bd63e44058c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='depuisOrdiPiecesJointes_maitriseFonciere']</value>
      <webElementGuid>b484dfdc-4c71-423e-9a1c-5aa2438cea85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploadBolc_PiecesJointes_maitriseFonciere']/div/button/span</value>
      <webElementGuid>2f33a759-4341-478a-8245-78a66778bf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aide sur la saisie de la pièce jointe. Fichier de justificatif de maîtrise foncière.'])[1]/following::span[1]</value>
      <webElementGuid>8fed8866-401e-4aef-a70d-66334a2358f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter un fichier :'])[4]/following::span[3]</value>
      <webElementGuid>92783eda-74ad-44ea-8a0a-b12933d2808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pdf'])[4]/preceding::span[2]</value>
      <webElementGuid>af390ce9-6cd4-4f7a-9b90-e15e181d47e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/div[3]/div/button/span</value>
      <webElementGuid>f48b9a02-cf40-4b54-bd95-ffb76a41e8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'depuisOrdiPiecesJointes_maitriseFonciere' and (text() = '
										Depuis mon ordinateur' or . = '
										Depuis mon ordinateur')]</value>
      <webElementGuid>93094874-ca60-46d2-a92b-0b7002457d7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
