<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_vcVZ7dtext-aligncenter</name>
   <tag></tag>
   <elementGuidId>1e83ebad-6fc4-4c69-9a52-e83828aafba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o3j99.qarstb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('J', &quot;'&quot;, 'ai envie de rire')])[1]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28a28be1-f76b-444c-a2e5-09c87bb7116a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o3j99 qarstb</value>
      <webElementGuid>14d85c8f-2593-4e74-996f-76c0c995724a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.vcVZ7d{text-align:center}</value>
      <webElementGuid>cbbb8a51-e8d0-4ea8-93ee-0a30ffb75572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 qarstb&quot;]</value>
      <webElementGuid>40ecda50-94e6-43e9-bd47-5c494c85b0ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('J', &quot;'&quot;, 'ai envie de rire')])[1]/following::div[3]</value>
      <webElementGuid>542dfe45-ef5e-4100-ac8c-6c0c3e36e952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Résultats artistiques'])[1]/following::div[4]</value>
      <webElementGuid>c1c4d070-18fd-4a54-8ab7-8ed3a15f72aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='France'])[1]/preceding::div[1]</value>
      <webElementGuid>378facac-5fae-4c73-aaa1-5c9299564227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='À propos'])[1]/preceding::div[2]</value>
      <webElementGuid>79f7db3a-6343-4624-86c2-6c96e9940575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div[4]</value>
      <webElementGuid>de378a70-bb40-4e0b-b3f2-e691ec460e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '.vcVZ7d{text-align:center}' or . = '.vcVZ7d{text-align:center}')]</value>
      <webElementGuid>205e8de7-d1b0-479c-9daa-a7a994072178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
