<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saisie complmentaire requise - affich_b44dc9</name>
   <tag></tag>
   <elementGuidId>538c8a6f-91ff-46b9-8fe0-197db76c93b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioTypeEtude0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioTypeEtude0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afef6f7a-2097-4e7a-ad3f-1459c95177e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>48fad780-b1b1-4b16-b631-595c90d0a871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>fe56a34c-2280-4e61-a90c-5aec161b6f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>22902f80-26b6-435f-9e9b-e7ba170f4888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-condition</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0cb72e5b-6ce2-407f-aad4-e6e9e37980b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioTypeEtude0</value>
      <webElementGuid>46342389-e1a4-4452-b73b-8822b0f837bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>99b7110b-b0f3-4795-8fc7-af6aa9510f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeComprendEtudeImpactOuEtudeIncidence</value>
      <webElementGuid>b879081f-2921-4fe5-bc7d-5100807f8c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>a2fb8636-19bd-4ded-a931-596704c3fd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioTypeEtude0&quot;)</value>
      <webElementGuid>333d4e3e-4724-4690-9184-8f210052c59b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioTypeEtude0']</value>
      <webElementGuid>ca24fe75-5d70-453f-b46b-3d2ab4de9ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioTypeEtude0']/input</value>
      <webElementGuid>bfa848b5-a3a4-4545-b590-00205623cd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>769317bd-dbc2-48ab-af58-b980351f1d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioTypeEtude0' and @name = 'demandeComprendEtudeImpactOuEtudeIncidence' and @checked = 'checked']</value>
      <webElementGuid>98743c3e-8551-42ef-91f8-0180b4723cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
