<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saisie complmentaire requise - affich_38b3fd</name>
   <tag></tag>
   <elementGuidId>6e7eb49c-d36f-48b3-8ec2-eb46be2d7137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioEtudeImpactRaison0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioEtudeImpactRaison0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dd27fbf-b2f9-40bb-b388-2081c0b826fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c6d230ef-3de8-4e16-9892-8317635bf082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>84a8319f-50b1-479e-9f83-37d3616926b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c208fd6a-5055-4d03-a45a-ae6689c7e1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target</name>
      <type>Main</type>
      <value>#etude_COND04_1</value>
      <webElementGuid>440ca769-3180-4e6d-ad9c-6c5d960febb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-condition</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e5f0d189-c862-4a68-ad3e-3261d354d51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioEtudeImpactRaison0</value>
      <webElementGuid>0db5568a-664c-4c6f-9ea5-c589fe33f324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bbf8b3e8-b3d8-432a-a717-f5e3a7f6c598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeEtudeImpactRaison</value>
      <webElementGuid>1a9d8aaa-4d46-45e1-a894-ff2c3fc10f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioEtudeImpactRaison0&quot;)</value>
      <webElementGuid>294c83f4-74e8-4c1e-bd46-e8ce94b04785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioEtudeImpactRaison0']</value>
      <webElementGuid>af91fcb8-80c8-420e-b3c0-e66c2b79b536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioEtudeImpactRaison0']/input</value>
      <webElementGuid>474b00f7-7139-437c-ac28-022b28839f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/label/input</value>
      <webElementGuid>9333b5a1-f905-43ee-944d-2a5f0ecd2713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioEtudeImpactRaison0' and @name = 'demandeEtudeImpactRaison']</value>
      <webElementGuid>4e3eff10-b205-4331-940a-2f2b9a14fb6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
