<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Etude dimpact</name>
   <tag></tag>
   <elementGuidId>2fdb6261-8d5b-46be-af40-4442fbe97af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbl_radioTypeEtude0 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lbl_radioTypeEtude0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ecaf515-d717-4275-ac4f-9dbeb2a937cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Etude d'impact</value>
      <webElementGuid>4e6f57ae-40a5-4336-8a8f-97c313a98589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbl_radioTypeEtude0&quot;)/span[1]</value>
      <webElementGuid>068ead9e-97d9-423d-a08e-1d24f4bddc00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioTypeEtude0']/span</value>
      <webElementGuid>d380a1f6-1993-42f4-b7f5-b24fcbe910d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saisie complémentaire requise - affichage automatique'])[1]/following::span[1]</value>
      <webElementGuid>7e057f84-4210-40f9-85f0-b7fcbc69e456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Quel type d', &quot;'&quot;, 'étude comprend votre demande ?')])[1]/following::span[2]</value>
      <webElementGuid>742afa99-6d9a-471b-b62b-d0d4874e90a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Etude d', &quot;'&quot;, 'incidence')])[1]/preceding::span[1]</value>
      <webElementGuid>1686e9c6-c5a7-498d-8343-b9e2c78b5430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[2]</value>
      <webElementGuid>04ccbafe-fafd-4ae1-bbf8-c730cc28e39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>cf83e756-5d2f-4adc-abdd-7c684aa2c16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;Etude d&quot; , &quot;'&quot; , &quot;impact&quot;) or . = concat(&quot;Etude d&quot; , &quot;'&quot; , &quot;impact&quot;))]</value>
      <webElementGuid>ff1de356-6dff-4f79-99b1-88f5d96b25c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
