<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_92400 - COURBEVOIE</name>
   <tag></tag>
   <elementGuidId>d351e66b-3334-4d55-8454-05f685a179e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a11y-suggestion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adressePP']/div/div/div/div/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae88d0b7-a58b-48f9-9912-ba94d2e492a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a11y-suggestion</value>
      <webElementGuid>b7432195-b25b-4d0e-aee4-523228936337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d4a9e671-f52b-4916-a061-e5feebdafc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b56ee3d1-0f69-49f5-b5df-35046d5d6650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>92400 - COURBEVOIE</value>
      <webElementGuid>5a1839d7-3fff-436f-82ec-a1e668bf1970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adressePP&quot;)/div[@class=&quot;composant&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;select-a11y&quot;]/div[@class=&quot;a11y-suggestions&quot;]/div[1]/div[@class=&quot;a11y-suggestion&quot;]</value>
      <webElementGuid>6e9ed481-c75b-497a-a90d-11c7ed2acd23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adressePP']/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>77bdbeac-e17f-4a92-bab4-040c8852820b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Exemple: 35510 CESSON SEVIGNE)'])[1]/following::div[5]</value>
      <webElementGuid>38d523f0-df75-4ab5-bf64-d151ba79d137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code postal / Localité'])[1]/following::div[5]</value>
      <webElementGuid>04a25831-5a86-4ca6-9ecf-88e4d29a07c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[24]/preceding::div[1]</value>
      <webElementGuid>afda15f7-12fa-43d2-bab6-71afb6edfafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='92400 -']/parent::*</value>
      <webElementGuid>7fce3e31-3bad-4735-8270-628c68655baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>31cbf2d2-8725-4626-ac51-7c1ee79fb8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '92400 - COURBEVOIE' or . = '92400 - COURBEVOIE')]</value>
      <webElementGuid>55d99698-1017-4406-a426-409023ef82a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
