<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adresse lectronique (exemple  nomexem_61b427</name>
   <tag></tag>
   <elementGuidId>45171b1f-d870-4bdf-a55f-dacb2b468e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputContactPersonnelCourriel_contactPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputContactPersonnelCourriel_contactPP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e3779db-77a6-43fe-91b4-aa7bc7984cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f146b2d0-9ea9-4fce-96f4-77d2f2231c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>19dd8b16-019e-4c57-b4b7-ccde91d5e0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control control-medium</value>
      <webElementGuid>439b0131-4fff-45df-9fff-1de8c932624a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputContactPersonnelCourriel_contactPP</value>
      <webElementGuid>ed12137c-9d9d-4245-98c8-ac44cbc7292f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>114ccc88-5da8-46d6-b568-e15cf68231fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>email tailleMax</value>
      <webElementGuid>5f5d4ca2-2b1c-4b6f-84aa-e4027b6d7baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d907d6a8-09f2-4d0c-a3c5-08ab69050cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>eea303d3-ab97-4f65-8218-515441bbc1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>textDanger161</value>
      <webElementGuid>571927b5-b06f-428a-aeb7-7cdbf4aa01fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a04af2b0-00aa-4d9b-9971-35dd56d5e443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>blocContactPP.courriel</value>
      <webElementGuid>f0fd2579-2816-450b-8cb9-b178dd0ca9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputContactPersonnelCourriel_contactPP&quot;)</value>
      <webElementGuid>3ef84bf5-f89f-4624-b898-4f44d7a23547</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputContactPersonnelCourriel_contactPP']</value>
      <webElementGuid>cb743331-f0c2-4012-8e54-48dc9cd0af4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blocIdentitePP']/div[11]/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>02166020-d55f-4472-9872-41e3b5e8f255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>8f568fe3-7908-48c4-a4df-701ee00d7fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputContactPersonnelCourriel_contactPP' and @name = 'blocContactPP.courriel']</value>
      <webElementGuid>91a8f33b-db9e-4d04-a5a7-a4c212cf864e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
