<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prnom_prenomPP</name>
   <tag></tag>
   <elementGuidId>ce115e7b-3f28-44ce-96ea-aa2cc9284b8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prenomPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prenomPP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69863bec-bc7a-412a-97ee-b010efc22c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-text-field</value>
      <webElementGuid>18505cd7-16ba-43f0-b086-90d5f89aa5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15a10e3c-44de-49e3-b662-0a85abca3e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prenomPP</value>
      <webElementGuid>2c27dae8-a0fc-4b86-9fee-c1a22186bf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prenomPP</value>
      <webElementGuid>4c843164-9c8c-4397-b299-51110ba770f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e61bde6c-05b4-4376-bf98-31cf9d3346fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>alpha04</value>
      <webElementGuid>dc2e08b1-7fa0-409f-a814-1cd99f904a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>690873c6-0ded-4b98-b9e8-2b2f16955e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prenomPP&quot;)</value>
      <webElementGuid>eb7a7cbf-f0f9-431e-a06c-9da28c963c6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prenomPP']</value>
      <webElementGuid>fdc5ec61-e380-461e-b1df-4d5f3d3ef1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_prenomPP']/input</value>
      <webElementGuid>962b1bf7-de6a-4a29-a374-c23463f2ab92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/label/input</value>
      <webElementGuid>9e8d1d5e-3d3a-4018-aa79-49a461e90fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'prenomPP' and @name = 'prenomPP']</value>
      <webElementGuid>9702f187-5baf-4d81-bbf9-35b038202b83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
