<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jour (JJ)_jourPP</name>
   <tag></tag>
   <elementGuidId>c00e6ea8-7cd3-47a9-a255-06ea14c069ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jourPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jourPP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f209808-925d-4d87-b887-c316a14b0de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72726b8f-6c1a-4bcb-b6d4-822958272b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90ea8999-891a-4d3f-ac71-ba5179cd1f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jourPP</value>
      <webElementGuid>115b0580-703e-4208-a378-9c26fe0e996b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jourPP</value>
      <webElementGuid>62f9ddb5-b757-4180-906d-bd7d59174697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fields</name>
      <type>Main</type>
      <value>#jourPP,#moisPP,#anneePP,#dateSection</value>
      <webElementGuid>9a429138-81e8-46ee-b5ea-19048fad0581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>entier valeurMin valeurMax customDate</value>
      <webElementGuid>9341aec1-a127-4bfa-9e2b-fed1cb594c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3c823f7b-4c41-4bbb-8d60-3c0d139f440d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-max</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>0f7952e6-df71-40eb-badd-9f0376bcc2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d3b0d47d-fca9-494b-a41a-d8e8380a7d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3ad97a34-94b8-46ee-9c89-6b22e8d99abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jourPP&quot;)</value>
      <webElementGuid>aec236b6-32e4-4032-af0d-3362185328ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jourPP']</value>
      <webElementGuid>ef368f80-603e-4fa7-8bb4-1357f7604375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateSection']/fieldset/div/div/input</value>
      <webElementGuid>049705fe-0d9c-4103-92bb-0f9ad2c87879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>3327364b-4536-40c8-b4e3-4a9ce3013f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jourPP' and @name = 'jourPP']</value>
      <webElementGuid>9dd995f0-dfb2-4386-ade5-12bdb49ec6ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
