<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fminin_sexePP</name>
   <tag></tag>
   <elementGuidId>72fa3537-1a48-43e4-b69d-14802b172296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioSexePP1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioSexePP1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d75bd25-68e8-468f-bcdb-098721b58108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>665d13a0-0a95-4f3d-85f6-b924d9129dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>643e7864-1815-4b89-bd26-3b8b447bfbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c52ead7c-6ea4-4e3e-a659-2c6f3b322034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioSexePP1</value>
      <webElementGuid>458dc314-b6d3-4565-86c7-e2dfc31491f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>homme</value>
      <webElementGuid>d801146c-db60-49b3-b63e-cc85a7de13d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sexePP</value>
      <webElementGuid>5c6e497e-9d60-458b-9bd6-b4bae9389fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioSexePP1&quot;)</value>
      <webElementGuid>e21785c1-171e-4a95-958c-327743599b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioSexePP1']</value>
      <webElementGuid>b277d14b-7e83-43c7-8dd2-b1b35f7f158f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioSexePP1']/input</value>
      <webElementGuid>8202da79-322b-45fa-8d50-c03481846805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/fieldset/label[2]/input</value>
      <webElementGuid>2f1a5f46-b0d8-4d67-8c67-dc74496a792d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioSexePP1' and @name = 'sexePP']</value>
      <webElementGuid>435a4d30-0701-4e00-974c-ca36a2dd3888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
