<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tlphone fixe (Exemple 123456789)_bloc_418839</name>
   <tag></tag>
   <elementGuidId>9f255c39-8b2b-49b6-81d6-234a161592b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputContactPersonnelTelephone_contactPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputContactPersonnelTelephone_contactPP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>119c4e09-ae3d-4e27-981a-9092b5fd988a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>eda18909-b4bc-42f3-bbae-d67efd120a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32e834df-9d56-4d92-a634-e72c63adf06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control telfixe</value>
      <webElementGuid>faf1a83b-a95f-42d0-aace-ff7e83c1a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputContactPersonnelTelephone_contactPP</value>
      <webElementGuid>4e645380-1245-4626-875a-0f88bdb11d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0764a62-bcfb-413e-9508-f16194e83ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>telephone</value>
      <webElementGuid>6ac1f4f5-3154-458b-af07-b9097cf3c141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>telFixeAvecIndicatif</value>
      <webElementGuid>c56718d8-66b8-423e-89dd-d11d742e2190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lk-required</name>
      <type>Main</type>
      <value>lkGroupcontactPP</value>
      <webElementGuid>f543630f-2ed4-4533-a349-dc61c1f786f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>7af5a6ee-5b13-4875-9cb4-0f6c159c91e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5e702efd-4326-44f6-9e54-a18f081eb64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>blocContactPP.telephoneFixe</value>
      <webElementGuid>8b7a7a9c-0f33-4638-8bac-c9504e41ef7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0506992-e728-4aad-9f1f-6a9bece11bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputContactPersonnelTelephone_contactPP&quot;)</value>
      <webElementGuid>06766766-8df8-468a-ade5-3231eabe8d4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputContactPersonnelTelephone_contactPP']</value>
      <webElementGuid>8f62a15a-4470-4f13-bdf9-88b1ab9517df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blocIdentitePP']/div[11]/div/div/div/div/fieldset/div/div/div[2]/div/div/input</value>
      <webElementGuid>4ae890c1-e3b8-487f-92ea-cc2e292ad96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/fieldset/div/div/div[2]/div/div/input</value>
      <webElementGuid>242ece4a-b05f-48e8-8bb2-e9338a3a49ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputContactPersonnelTelephone_contactPP' and @name = 'blocContactPP.telephoneFixe']</value>
      <webElementGuid>e3ae859a-a6b2-4cfa-9e95-524d59e91707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
