<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nom_nomPP</name>
   <tag></tag>
   <elementGuidId>33e89f8f-95a8-42cc-b9d7-760dbd395a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomPP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd0e6346-4d66-4ce0-89fb-13d7966cddf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-text-field</value>
      <webElementGuid>1cc799dc-b76f-4160-a113-f605a7e5bb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f336ba09-f397-4665-88b5-835199d81382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomPP</value>
      <webElementGuid>5953621b-89ab-4cc5-baea-89bd7ffb37ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomPP</value>
      <webElementGuid>aa651661-1925-4d8f-bb7b-cc1a76873187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0a0fb31c-9b31-4b84-badd-b03ec33bf35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>alpha04</value>
      <webElementGuid>e32eaacd-f3d4-44c5-9157-bcf24b0c721f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fdf08439-2d03-4db5-a236-54e2907c605e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomPP&quot;)</value>
      <webElementGuid>d7528494-0fb0-4f4b-b0ae-6bf1b36494b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomPP']</value>
      <webElementGuid>90fc0ad6-a238-4132-99a8-68b6c93fbe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_nomPP']/input</value>
      <webElementGuid>a1da46d2-f2a8-4149-a8bf-b2c48425009c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label/input</value>
      <webElementGuid>05931794-9961-4fc0-bdfe-1aec5abc9039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nomPP' and @name = 'nomPP']</value>
      <webElementGuid>e8a6dc33-c740-4de9-b135-6e5c2b03f429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
