<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Anne (AAAA)_anneePP</name>
   <tag></tag>
   <elementGuidId>70ea85c5-c76e-4981-b6c4-a37b59559292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anneePP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anneePP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c796bfa-3e00-40be-9d56-078245e42417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>99abc892-316a-44bd-b8ca-ad7e0bcf8081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89c8e876-1b58-4466-9829-baa8de7179c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anneePP</value>
      <webElementGuid>55deed41-a7a2-452d-b83a-c360f51661c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anneePP</value>
      <webElementGuid>65828686-b485-4951-8e16-d9749b4f7a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fields</name>
      <type>Main</type>
      <value>#jourPP,#moisPP,#anneePP,#dateSection</value>
      <webElementGuid>8895f570-0300-4d43-935e-080c930e8cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>entier tailleMin tailleMax customDate</value>
      <webElementGuid>c7216ebe-bb37-4e7a-af0d-59914271c564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-min</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3a2d1592-e700-43ee-8e36-3ada56b04551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-max</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5f8535ce-17bb-48b7-b236-562e37387638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0bd451a0-1378-48ed-8e11-fb7f5e91f18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7cbc07f8-b535-422e-aa52-1002c2957df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>textDanger123</value>
      <webElementGuid>b4a1dae9-5391-4797-8332-d0b9928a5692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b31b0d0-5643-48e0-9e33-69b719e5ecf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anneePP&quot;)</value>
      <webElementGuid>fd34c1dc-b9f0-4f1a-a3b3-403d2752ce82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anneePP']</value>
      <webElementGuid>8f4d0e63-69d6-4a43-9baa-401f161de635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateSection']/fieldset/div[3]/div/input</value>
      <webElementGuid>a83662a4-4341-437c-9315-8009c557ffff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>767ee572-a604-4e67-a742-65c000d83cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'anneePP' and @name = 'anneePP']</value>
      <webElementGuid>065f0f19-1d31-4241-ad2b-a44a26aa2238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
