<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Exemple  72 rue Balzac)_adressePP.voie</name>
   <tag></tag>
   <elementGuidId>82bd18a5-ec8f-47c8-8ed6-f6e5829345ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAdresseFrVoie_adressePP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAdresseFrVoie_adressePP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5dac7df-9fe4-41b1-b2e9-7e7670bd27bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f10f7497-9c1b-45c1-9cfb-4191567f9caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f04087b1-8e46-46d9-b88c-84aff16f1ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>alphanumeriquePlus</value>
      <webElementGuid>6fbf58b1-0188-4d64-9116-20d786238a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAdresseFrVoie_adressePP</value>
      <webElementGuid>0a67c565-96c7-42b9-ad15-794fa061837d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96a49946-57cf-455f-8a99-31f5a164020f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>30891fee-1179-47ea-9095-55d4c4fd692f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adressePP.voie</value>
      <webElementGuid>d9fe864d-c11e-4e06-a22a-c6364c221b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fc3bdb01-9beb-4f96-8e4f-f8b2ca30db3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e84c454d-7c80-44eb-ad5e-e027d0ba1a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAdresseFrVoie_adressePP&quot;)</value>
      <webElementGuid>9f7cbf93-bbcb-4ec8-92a3-4e0e23553577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAdresseFrVoie_adressePP']</value>
      <webElementGuid>93cbd8b9-76ac-44a7-84e2-3c2aa3ef1eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adressePP']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>457321d2-49aa-41bf-8e4a-830b99062c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>64e7ab7a-4891-4d80-821d-0579473d418e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAdresseFrVoie_adressePP' and @name = 'adressePP.voie']</value>
      <webElementGuid>c1b4e28b-cd3c-44b7-81e0-f5b4ef640df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
