<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Exemple 35510 CESSON SEVIGNE)_adress_68900f</name>
   <tag></tag>
   <elementGuidId>f2d60aea-c3ea-4636-8e57-94edb8c5e7bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAdresseFrLocaliteCP_adressePP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAdresseFrLocaliteCP_adressePP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af26c6d5-84e3-4102-b651-0fd0ad14cfdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8ab11c9e-9a24-49c7-9a92-bb8bc09f85df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autocomplete</value>
      <webElementGuid>f995fcc9-a4c8-4529-9a95-f440691584f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAdresseFrLocaliteCP_adressePP</value>
      <webElementGuid>a8925d75-25ea-4ff9-9ebc-b085be26686e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fceb2232-24b1-4a18-a3fd-3f39437fc11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>localiteCodePostal tailleMax</value>
      <webElementGuid>55a15d52-f465-4a5c-9ff1-eb9c03e500db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-max</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>8a084bb8-9f99-4356-986e-c501e72731f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>b105b3d1-e079-4cb9-b993-c3975485cd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autocomplete-type</name>
      <type>Main</type>
      <value>communeOrCP</value>
      <webElementGuid>70feceae-cd90-4c3c-8580-13a834c4ccd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>communeCP</value>
      <webElementGuid>254758be-3fab-439a-a1a6-8ea4838804d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>messageinputAdresseFrLocaliteCP_adressePP</value>
      <webElementGuid>98a708e5-4b85-4a0f-801a-9757604ef8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9b320ad4-774c-4de6-afbb-26471e453557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adressePP.localiteCP</value>
      <webElementGuid>0f663f5c-e1de-4106-b3db-1b497b8f42f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enableautocompletev2</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>467e1387-40a0-48b4-a57c-06d35ba9f6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAdresseFrLocaliteCP_adressePP&quot;)</value>
      <webElementGuid>02b4ffd0-c04e-4629-8d43-c2b40f48e57a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAdresseFrLocaliteCP_adressePP']</value>
      <webElementGuid>febf0986-e6c9-4b99-bdef-14afed367b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adressePP']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>96c7e59e-726d-4b4c-b87f-35a920c0df58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>0e531d2f-a42d-493e-be97-f55871775717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'inputAdresseFrLocaliteCP_adressePP' and @name = 'adressePP.localiteCP']</value>
      <webElementGuid>efa709c5-1647-4538-9d35-d24ba3e4f36b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
