<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saisie complmentaire requise - affich_75517a</name>
   <tag></tag>
   <elementGuidId>77bf9303-7e44-4219-bacf-bac54e8cae0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioPP0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioPP0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40bb8fd7-9ed6-49f3-a307-10dbaf7cd9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b8407109-0b68-4ce3-a58a-76d767f46360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>7139f746-a14f-471e-96e7-c8c0d7152f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cefaf9cb-6b3c-44b1-856a-ee711a643061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target</name>
      <type>Main</type>
      <value>#adressePP,#chSiretPP</value>
      <webElementGuid>273b3b6f-bdab-45fa-ba84-30d85806662f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target-inverse</name>
      <type>Main</type>
      <value>#adresseEtrPP</value>
      <webElementGuid>ab19935a-8958-46f9-ad1a-c0a30a0e9681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-condition</name>
      <type>Main</type>
      <value>france</value>
      <webElementGuid>7bcd94d2-99b1-45c2-959a-90c1d08aa6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioPP0</value>
      <webElementGuid>528a20a1-4512-47db-88cf-3a45c71dae53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>france</value>
      <webElementGuid>862c7feb-2094-4884-95ec-45476d037051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chTypeAdressePP</value>
      <webElementGuid>5fec16e9-d966-4974-8df0-ee60abdf9ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioPP0&quot;)</value>
      <webElementGuid>57ec7bbf-edf5-4108-a655-181cd2b329db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioPP0']</value>
      <webElementGuid>bd49555e-574c-4d35-b8e1-15ed5e31532f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioPP0']/input</value>
      <webElementGuid>f37f9ba3-2eca-4cf9-bc2d-7aee719091bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/fieldset/label/input</value>
      <webElementGuid>56f5263b-545c-4a5b-a5fe-a54ca27162a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioPP0' and @name = 'chTypeAdressePP']</value>
      <webElementGuid>b6f1ce8c-ca7a-4087-8401-8dd176f520ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
