<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adresse lectronique (exemple  nomexem_00dd2b</name>
   <tag></tag>
   <elementGuidId>bffa72ca-fba8-4f79-968e-ee76833d0da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_mail_admin_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_mail_admin_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95efd9ab-b144-4bd9-b0c7-6037392e75c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c1f3541a-9ff5-44c7-9a64-26cc77d518ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bloc-mail-admin-info</value>
      <webElementGuid>6d5b9c84-a12e-4fa5-9f68-93a5a2e6fa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_mail_admin_id</value>
      <webElementGuid>dc6f9f33-8a26-449b-9693-61ce725b3e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_mail_admin_id&quot;)</value>
      <webElementGuid>492c8ca9-4bc1-41e1-81d1-72e445b9d7c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_mail_admin_id']</value>
      <webElementGuid>c2f79169-869b-4e8c-bd19-d0893ab88be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[3]/form/div[2]/div[7]/div[2]/div/label/input</value>
      <webElementGuid>a6fc103e-d44f-4b2b-80de-7ddb52084338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/label/input</value>
      <webElementGuid>e8fa0426-576b-4502-a7c2-8c156eb0c589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'input_mail_admin_id']</value>
      <webElementGuid>aedfc76d-4c82-4227-86d8-a39787e46e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
