<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tlphone portable (Exemple 623456789)__fd3d17</name>
   <tag></tag>
   <elementGuidId>4985723d-080c-4116-bf20-92e09777d915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputContactPersonnelMobile_contactPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputContactPersonnelMobile_contactPP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b74e4c6-ac38-452d-8f8e-a84d4ed047ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35fcad34-2472-40d5-a714-0965dff7a8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>47603b0f-28a9-464a-8b8b-ac3dde800a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control telportable</value>
      <webElementGuid>23614afe-e079-47fe-a470-cdc967743b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputContactPersonnelMobile_contactPP</value>
      <webElementGuid>b5751246-8a88-4105-9a66-56fd973134e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6f2a4af-e206-494f-9d4e-b2d19dbe2003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>telephone</value>
      <webElementGuid>5a8a399a-bd71-414e-9621-e5db7d8c886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>telPortableAvecIndicatif</value>
      <webElementGuid>aa75f9d7-32a0-4a78-9a77-a8b55fe9a6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lk-required</name>
      <type>Main</type>
      <value>lkGroupcontactPP</value>
      <webElementGuid>ec89335b-4fc3-4b03-af1f-24d4a6954234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>17a15482-7158-4b41-a3e0-49bb207505a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>blocContactPP.telephonePortable</value>
      <webElementGuid>804afb69-0af8-49c8-9970-86ed6052ccf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d0cf49f-7e7b-4dbf-aea7-bf6191f54091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputContactPersonnelMobile_contactPP&quot;)</value>
      <webElementGuid>518af134-286e-43b0-8821-0a65f8cf6279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputContactPersonnelMobile_contactPP']</value>
      <webElementGuid>b0bcb1e4-2ccc-4c9c-9fa8-a181f1535970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blocIdentitePP']/div[11]/div/div/div/div/fieldset/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>b6f466c9-fbd4-4d8f-97dc-71ac11152266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/fieldset/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>e98345f4-6a51-42a5-867b-8a781c325bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputContactPersonnelMobile_contactPP' and @name = 'blocContactPP.telephonePortable']</value>
      <webElementGuid>639c4e69-c673-403d-acc3-e0142f1a021f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
