<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mois (MM)_moisPP</name>
   <tag></tag>
   <elementGuidId>4901f1aa-951f-46da-b725-6dd1783b8825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moisPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='moisPP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9601bad-6a02-4921-9162-2b223f70368d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>998dd669-fcbb-4bc6-a580-776040cd4fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ca6f625-62af-4ec9-82d9-ee0fd7ee846a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moisPP</value>
      <webElementGuid>cf58f94a-47ef-4604-83b0-6220ba831a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moisPP</value>
      <webElementGuid>52325cd1-eb0e-4580-ac7a-dbe7bdfda11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fields</name>
      <type>Main</type>
      <value>#jourPP,#moisPP,#anneePP,#dateSection</value>
      <webElementGuid>7cf829ad-1268-4c47-80e1-8e93e4482e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>entier valeurMin valeurMax customDate</value>
      <webElementGuid>4eeb7d0d-2ea7-4008-ba91-7a4632fcb536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f9132a87-e08d-469f-b12b-445861491f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format-max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>681078dd-a24b-41ca-a2d2-1b6143b0cb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d67ad21e-92b3-448b-bec7-90c6a6ba3989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>73da54b7-3553-4431-a0fc-89d289bb3752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moisPP&quot;)</value>
      <webElementGuid>5b0ca635-ef4f-469d-9671-4575efff88fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='moisPP']</value>
      <webElementGuid>99aa75bd-3147-4c57-b653-e10e5865dff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateSection']/fieldset/div[2]/div/input</value>
      <webElementGuid>bd6e69f4-ac50-4695-87fb-f303c5d9a969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>dffa3636-3216-4b52-99f4-1781a52a4525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'moisPP' and @name = 'moisPP']</value>
      <webElementGuid>e32f061f-5f39-43a2-9092-86304160f16e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
