<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personne morale_chPersonne</name>
   <tag></tag>
   <elementGuidId>1aaab802-21bf-4857-87d0-643e8898da68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioTPers1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioTPers1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81610330-1359-4753-8189-5180618d441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0842b1b4-7402-4eeb-bfa1-f2fc71194375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>92abc728-0572-4545-8e8b-4bb701a78e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e8c8010d-8a83-4723-b8b0-97f01cf745ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target</name>
      <type>Main</type>
      <value>#pers_COND01_NON</value>
      <webElementGuid>5a63e30a-929e-4d49-aa69-a006bdb4d9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target-inverse</name>
      <type>Main</type>
      <value>#pers_COND01_OUI,#pers_COND01_OUI_REFERENT</value>
      <webElementGuid>b3df300a-b461-4d35-829c-38b38426e373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-condition</name>
      <type>Main</type>
      <value>NON</value>
      <webElementGuid>a0d38dae-4c44-4151-8830-f45cc822827b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioTPers1</value>
      <webElementGuid>7b98623c-84e8-4c54-92d8-fd8ca522baaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NON</value>
      <webElementGuid>0581d7d3-635c-4158-8aeb-fe4eb71a5d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chPersonne</value>
      <webElementGuid>edbb64e8-6beb-45d7-b3d0-f5a0a541d26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioTPers1&quot;)</value>
      <webElementGuid>559510e5-22f5-4aab-82a5-14c15e5ef7fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioTPers1']</value>
      <webElementGuid>635fa859-2348-4cfc-acf2-5cef9cfbd4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioTPers1']/input</value>
      <webElementGuid>4fb8c17c-97f7-4c44-9728-c6f16c2d81b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/fieldset/label[2]/input</value>
      <webElementGuid>77f337d0-e827-44f5-b766-11f28df5ab1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioTPers1' and @name = 'chPersonne']</value>
      <webElementGuid>80903b7c-0299-4efd-a4a6-60642bec19e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
