<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lieu-dit  boite postale  commune dlgu_58bd2d</name>
   <tag></tag>
   <elementGuidId>fbb348c7-559d-4471-bb27-38f97916cfc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAdresseFrLieu_adressePP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAdresseFrLieu_adressePP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ee83462-4a3d-417c-a65a-66f3533b9612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebdc03f5-9c6b-476a-a66a-a7236289635e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c008527c-29ba-43ab-bbd9-ffdbad7cf473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>alphanumeriquePlus</value>
      <webElementGuid>bca018c4-d26f-49d4-9399-c621967e5df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAdresseFrLieu_adressePP</value>
      <webElementGuid>7e9f6371-0db7-4165-80a2-2a7da965b18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b67802d0-561d-4161-b5bf-68cb640f99c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d754a6a4-4009-4e2c-8ee7-51ecc132ff94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adressePP.lieuDit</value>
      <webElementGuid>3333f0a9-8e29-48bb-b010-1c82696b360a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>707ecb92-0353-4384-9d09-65e9a15a2d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAdresseFrLieu_adressePP&quot;)</value>
      <webElementGuid>0affbf12-9d11-4501-9ef3-216aa5551fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAdresseFrLieu_adressePP']</value>
      <webElementGuid>fa3af5e5-8e38-46d1-b8dd-b0ed76fb1e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adressePP']/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>c0d04cbd-762f-4fd3-b9c3-a2b62358e214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>7723d1c4-d571-4c57-afc5-a7662c6eaa9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAdresseFrLieu_adressePP' and @name = 'adressePP.lieuDit']</value>
      <webElementGuid>3c4f377b-7802-472b-a6e6-312ec94e4bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
