<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oui_chNPetitionnaire</name>
   <tag></tag>
   <elementGuidId>bfaf28b3-f02f-42e1-bf12-7c386f085371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_radioNP1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_radioNP1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0aebe0b5-9ae3-4907-863e-1a8fc4072c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>111ef008-750f-4171-816f-5a6e6b09d2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handler</value>
      <webElementGuid>1eefd339-eacc-41d6-bc06-ac748ecb1102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6c438abd-45a5-4769-858c-1ed0a88267db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target</name>
      <type>Main</type>
      <value>#nptcnr_COND01_NON</value>
      <webElementGuid>fdf77d0b-1cb2-43dc-bf11-0104887373dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-target-inverse</name>
      <type>Main</type>
      <value>#nptcnr_COND01_OUI</value>
      <webElementGuid>b6000a30-0ca8-432d-bc1e-1901baf98ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler-condition</name>
      <type>Main</type>
      <value>NON</value>
      <webElementGuid>308037df-d6f7-4e5d-8323-1e07a3bc7c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_radioNP1</value>
      <webElementGuid>12cd29b5-0343-4db7-8c34-59d610879561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NON</value>
      <webElementGuid>ee74f137-3e36-46f1-9918-8c457196d991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chNPetitionnaire</value>
      <webElementGuid>c9991f91-6885-4546-94cf-e12094df77e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_radioNP1&quot;)</value>
      <webElementGuid>dad57015-7e45-4b5a-9a79-0eb044f6e4cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_radioNP1']</value>
      <webElementGuid>d79f3f51-5c26-41e2-9b91-a367ad484c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lbl_radioNP1']/input</value>
      <webElementGuid>e17f5d9e-26a3-41a0-a495-eb99f5011c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/label[2]/input</value>
      <webElementGuid>91946472-95f0-4471-a8cc-4e9e4b7f6f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'input_radioNP1' and @name = 'chNPetitionnaire']</value>
      <webElementGuid>632425e5-914d-4fa4-8395-2f68cc808093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
