<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Suivant</name>
   <tag></tag>
   <elementGuidId>c3a0f53e-02ab-453e-809e-0b1c5e957cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suivant > span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='suivant']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>454fbdd9-a1d9-410b-aed7-70572a27f0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>b86e5d27-a548-42b7-8fd3-001118e8aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>eb28403e-665b-4963-a220-3d48866c31da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suivant&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>3e6412e0-abe2-44dc-87a3-d071621c5ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='suivant']/span</value>
      <webElementGuid>6004a874-d129-434c-ba5c-1a138bcc8b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Précédent'])[1]/following::span[1]</value>
      <webElementGuid>7b74f60f-1743-4a51-a0aa-4ff28f21497c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresse électronique (exemple : nom@exemple.com)'])[5]/following::span[2]</value>
      <webElementGuid>28927faa-0944-42da-8b56-b7ab95588ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lettre Service-Public'])[1]/preceding::span[2]</value>
      <webElementGuid>01f91c1e-ada7-4e9a-be87-e42de4c9289c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::span[3]</value>
      <webElementGuid>e99d08af-cd9c-4d44-8e02-61ef5ab190bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suivant']/parent::*</value>
      <webElementGuid>6e490f80-dbee-4829-9ff1-e6f697b73c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button[2]/span</value>
      <webElementGuid>2b7fd298-46a6-4755-ad3f-75891ee73c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Suivant' or . = 'Suivant')]</value>
      <webElementGuid>75bbfb19-4e79-4d1d-9fe4-27bd4160294b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
