<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Veuillez renseigner les caractres aff_c59c5c</name>
   <tag></tag>
   <elementGuidId>4dd9122e-2320-4f3e-9227-71c24a5a9d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captchaFormulaireExtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captchaFormulaireExtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>710a4449-30bf-41a5-b0b1-0a7d39031060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captchaFormulaireExtInput</value>
      <webElementGuid>6b364b57-5ca4-41e6-b369-fef180fb6bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90ae5df6-e6b1-4742-ac47-c843659cff92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2dba9a0f-0063-4bda-b7fc-3d061ca0ed18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha.captchaSaisi</value>
      <webElementGuid>d04c16b5-dbb2-4790-9637-394663061849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>erreurCaptcha</value>
      <webElementGuid>4fea901a-616d-4f54-b5cc-4fdfd56119ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3ed01bc2-8b7a-45a6-bd74-0506f1d0bbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captchaFormulaireExtInput&quot;)</value>
      <webElementGuid>aa523bc5-1c89-4441-b468-4459a8fb16f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captchaFormulaireExtInput']</value>
      <webElementGuid>705c72a2-48ae-4a72-8d4c-abef81e95dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div/div/form/div/div[2]/div/div/input</value>
      <webElementGuid>e6e85f21-495f-488c-8a41-868438b217c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>4777befc-e335-48bf-a46b-c504f14a7fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'captchaFormulaireExtInput' and @type = 'text' and @name = 'captcha.captchaSaisi']</value>
      <webElementGuid>98dddf7b-ee73-4ffa-a072-2c758550fe2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
