<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Suivant</name>
   <tag></tag>
   <elementGuidId>51d0d4e3-aa28-4fe8-99fe-27b63d037430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suivant > span.btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='suivant']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45747462-bb04-4ad7-8b59-26bc0dd0633e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>a00759e3-923e-4f11-8041-465ca3a39586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>4554686d-2427-4064-9223-462b277d6546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suivant&quot;)/span[@class=&quot;btn-text&quot;]</value>
      <webElementGuid>bb8a2b0a-4b95-48e9-88c2-c5758bb2775c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='suivant']/span</value>
      <webElementGuid>aaa8c016-da24-4a22-9b14-20eaabd3157b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reprendre plus tard'])[1]/following::span[1]</value>
      <webElementGuid>d0a81712-0c88-476b-a74e-0ae33af9296c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Précédent'])[1]/following::span[2]</value>
      <webElementGuid>c7877894-51f9-4b95-a3c8-e4ffba76de9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lettre Service-Public'])[1]/preceding::span[2]</value>
      <webElementGuid>fd98192d-7a60-4e74-bc63-2db87abef3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::span[3]</value>
      <webElementGuid>1c800f40-6150-46d0-bfbd-8ede8b4a3958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suivant']/parent::*</value>
      <webElementGuid>d45a086b-395a-48ba-9bd8-ffcb51cf57fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button[3]/span</value>
      <webElementGuid>972b31b9-e821-4bac-8f8f-586d4cd09a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Suivant' or . = 'Suivant')]</value>
      <webElementGuid>3b8ed0ce-82d4-4d2f-9482-e76f21aee939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
